local name = require('name')
print(name.firstname())
print(name.lastname())
print(name.fullname(true))
print(name.cfirstname())
print(name.clastname())
print(name.cfullname())
print(name.cfullname())

local base = require('base')
print(base.bool())
print(base.natural(10, 20))
print(base.natural(-10, 200))
print(base.int(10, 20))
print(base.int(10, 2))
print(base.char('all'))
print(base.char())
print(base.char('ab@#$%^&*cdefghijk'))
print(base.string('ab@#$%^&*cdefghijk', 3, 6))

local address = require('address')
print(address.region())
print(address.zip())
print(address.province())
print(address.city())
print(address.city(true))
print(address.county())
print(address.county(true))
print(address.countyId())

local text = require('text')
print(text.word())
print(text.cword())

local web = require('web')
print(web.URL())
print(web.protocol())
print(web.domain())
print(web.TLD())
print(web.email())
print(web.IP())

local date = require('date')
print(date.date())
print(date.date('yyyyMMdd'))
print(date.date('yyyy年MM月dd日'))
print(date.time())
print(date.time('HH:mm'))
print(date.datetime())
print(date.now())

local misc = require('misc')
print(misc.GUID())
print(misc.UUID())
print(misc.ID())
print(misc.incr())
print(misc.incr())
print(misc.incr(5))