local name = require('name')
print(name.firstname())
print(name.lastname())
print(name.fullname(true))
print(name.cfirstname())
print(name.clastname())
print(name.cfullname())
print(name.cfullname())
print('======== test name end')

local basic = require('basic')
print(basic.bool())
print(basic.natural(10, 20))
print(basic.natural(-10, 200))
print(basic.int(10, 20))
print(basic.int(10, 2))
print(basic.char('all'))
print(basic.char())
print(basic.char('ab@#$%^&*cdefghijk'))
print(basic.string('ab@#$%^&*cdefghijk', 3, 6))
print('======== test basic end')

local address = require('address')
print(address.region())
print(address.zip())
print(address.province())
print(address.city())
print(address.city(true))
print(address.county())
print(address.county(true))
print(address.countyId())
print('======== test address end')

local text = require('text')
print(text.word())
print(text.cword())
print(text.title())
print(text.ctitle())
print('======== test text end')

local web = require('web')
print(web.URL())
print(web.protocol())
print(web.domain())
print(web.TLD())
print(web.email())
print(web.IP())
print('======== test web end')

local date = require('date')
print(date.date())
print(date.date('yyyyMMdd'))
print(date.date('yyyy年MM月dd日'))
print(date.time())
print(date.time('HH:mm'))
print(date.datetime())
print(date.now())
print('======== test date end')

local misc = require('misc')
print(misc.GUID())
print(misc.UUID())
print(misc.ID())
print(misc.incr())
print(misc.incr())
print(misc.incr(5))
print('======== test misc end')